### ISSUE TITLE
can't found SW device

### ISSUE THREAD

**Issue by amigomcu** [wuxx/nanoDAP-wireless#1]
hi 
i try to connect nano Dap wireless , but can't found SW device
the pc host should be found,and then LED blue is on.

nano-DAP v2.3

keil c
https://i.imgur.com/qpT1bzK.png
device list
https://i.imgur.com/lx22L0I.png

win10 pro
keil uVision V5.15

**Comment by wuxx** [comment]
https://i.imgur.com/qpT1bzK.png 
this screenshot means that the dap wireless is ok, but it can not detect your target board. 
usually it's the wire problem or the power supply is not enough.
