### ISSUE TITLE
对你使用nordic24l01表示疑惑

### ISSUE THREAD

**Issue by Hemingway2003** [wuxx/nanoDAP-wireless#2]
类似的项目大学的时候做过，当时还不流行cmsis-dap，用的是仿照st-link的协议
当时最开始也是使用的24l01作为无线，但是要做到全双工的收发我是使用的两对24l01，因为经过测试该芯片只支持半双工（同频带的似乎都做不到）
但是看你首页使用的是wifi芯片，似乎是esp系列的
如果用该系列的芯片，我记得有esp32-s2，阉割了蓝牙，支持usb接口

**Comment by wuxx** [comment]
dap协议是请求-应答，可以用半双工来实现。
esp32-s2已经实现，后续会推出。
