### ISSUE TITLE
波特率为某些值时, 串口无法使用

### ISSUE THREAD

**Issue by tonyddg** [wuxx/nanoDAP-wireless#6]
MCU STM32F103C8T6
发送端与接收端的波特率为115200 时, 无法触发串口的 RXNE 中断
波特率为9600时也可能无法触发 RXNE 中断, 反而波特率为 115600 后恢复正常 
是因为仿真器只能使用特定的波特率吗, 如果是的话如何设置?

**Comment by wuxx** [comment]
可以抓波形看看，或者无线下载器自发自收测试看看，应该是可以的
